spring:
  jpa:
    hibernate:
      hbm2ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:crm
    driverClassName: org.h2.Driver
    platform: h2
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2-console
server:
  port: '2308'
